// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6UWZHMoBUO5dUoSpD_dIpV8YM6ivrsHI',
    appId: '1:154184418400:web:e494258fd722ac6664ef05',
    messagingSenderId: '154184418400',
    projectId: 'collegemanagementsaas',
    authDomain: 'collegemanagementsaas.firebaseapp.com',
    storageBucket: 'collegemanagementsaas.firebasestorage.app',
    measurementId: 'G-FNY8Q5KQVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBu7PjqxGZFnc75d-0j_TnNYb86RdXjjw',
    appId: '1:154184418400:android:20009f42b7640c4764ef05',
    messagingSenderId: '154184418400',
    projectId: 'collegemanagementsaas',
    storageBucket: 'collegemanagementsaas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4_jqzecKSG9NchgksG0ectZesV8f-cg8',
    appId: '1:154184418400:ios:3676c00e175cfb9964ef05',
    messagingSenderId: '154184418400',
    projectId: 'collegemanagementsaas',
    storageBucket: 'collegemanagementsaas.firebasestorage.app',
    iosBundleId: 'com.example.collegeManagementSaas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4_jqzecKSG9NchgksG0ectZesV8f-cg8',
    appId: '1:154184418400:ios:3676c00e175cfb9964ef05',
    messagingSenderId: '154184418400',
    projectId: 'collegemanagementsaas',
    storageBucket: 'collegemanagementsaas.firebasestorage.app',
    iosBundleId: 'com.example.collegeManagementSaas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6UWZHMoBUO5dUoSpD_dIpV8YM6ivrsHI',
    appId: '1:154184418400:web:ff33d6dbfeddb7fa64ef05',
    messagingSenderId: '154184418400',
    projectId: 'collegemanagementsaas',
    authDomain: 'collegemanagementsaas.firebaseapp.com',
    storageBucket: 'collegemanagementsaas.firebasestorage.app',
    measurementId: 'G-H48YZE6N31',
  );
}
